# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginMVVMC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAuth'

  # Pods for LoginMVVMC

  target 'LoginMVVMCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginMVVMCUITests' do
    # Pods for testing
  end

end
